variable "resource_group" {}
variable "location" {}
variable "vnetip" {}
variable "websubnet" {}
variable "appsubnet" {}
variable "dbsubnet" {}
variable "web_subnet_id" {}
variable "app_subnet_id" {}
variable "db_subnet_id" {}
